Document: rodebian
Title: Debian rodebian Manual
Author: <insert document author here>
Abstract: This manual describes what rodebian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rodebian/rodebian.sgml.gz

Format: postscript
Files: /usr/share/doc/rodebian/rodebian.ps.gz

Format: text
Files: /usr/share/doc/rodebian/rodebian.text.gz

Format: HTML
Index: /usr/share/doc/rodebian/html/index.html
Files: /usr/share/doc/rodebian/html/*.html
